/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogDeploiementFullStackGkeGitopsRouteImport } from './routes/blog/deploiement-full-stack-gke-gitops'
import { Route as BlogGkeGitopsFullStackDeploymentRouteImport } from './routes/blog/gke-gitops-full-stack-deployment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDeploiementFullStackGkeGitopsRoute =
  BlogDeploiementFullStackGkeGitopsRouteImport.update({
    id: '/blog/deploiement-full-stack-gke-gitops',
    path: '/blog/deploiement-full-stack-gke-gitops',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGkeGitopsFullStackDeploymentRoute =
  BlogGkeGitopsFullStackDeploymentRouteImport.update({
    id: '/blog/gke-gitops-full-stack-deployment',
    path: '/blog/gke-gitops-full-stack-deployment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/deploiement-full-stack-gke-gitops': typeof BlogDeploiementFullStackGkeGitopsRoute
  '/blog/gke-gitops-full-stack-deployment': typeof BlogGkeGitopsFullStackDeploymentRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/deploiement-full-stack-gke-gitops': typeof BlogDeploiementFullStackGkeGitopsRoute
  '/blog/gke-gitops-full-stack-deployment': typeof BlogGkeGitopsFullStackDeploymentRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/deploiement-full-stack-gke-gitops': typeof BlogDeploiementFullStackGkeGitopsRoute
  '/blog/gke-gitops-full-stack-deployment': typeof BlogGkeGitopsFullStackDeploymentRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experience'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/deploiement-full-stack-gke-gitops'
    | '/blog/gke-gitops-full-stack-deployment'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experience'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/deploiement-full-stack-gke-gitops'
    | '/blog/gke-gitops-full-stack-deployment'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/experience'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/deploiement-full-stack-gke-gitops'
    | '/blog/gke-gitops-full-stack-deployment'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogDeploiementFullStackGkeGitopsRoute: typeof BlogDeploiementFullStackGkeGitopsRoute
  BlogGkeGitopsFullStackDeploymentRoute: typeof BlogGkeGitopsFullStackDeploymentRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/deploiement-full-stack-gke-gitops': {
      id: '/blog/deploiement-full-stack-gke-gitops'
      path: '/blog/deploiement-full-stack-gke-gitops'
      fullPath: '/blog/deploiement-full-stack-gke-gitops'
      preLoaderRoute: typeof BlogDeploiementFullStackGkeGitopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gke-gitops-full-stack-deployment': {
      id: '/blog/gke-gitops-full-stack-deployment'
      path: '/blog/gke-gitops-full-stack-deployment'
      fullPath: '/blog/gke-gitops-full-stack-deployment'
      preLoaderRoute: typeof BlogGkeGitopsFullStackDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogDeploiementFullStackGkeGitopsRoute:
    BlogDeploiementFullStackGkeGitopsRoute,
  BlogGkeGitopsFullStackDeploymentRoute: BlogGkeGitopsFullStackDeploymentRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
